Algoritmo "exercicioFaccat5"
// Disciplina   : [Lógica da programação com javascript]
// Professor   : Jailson Costa dos Santos
// Descrição   :  Ler o antecessor de um número
// Autor(a)    : Grazielly Raissa Pereira de souza
// Data atual  : 24/03/2024
Var
   numero, antecessor:inteiro

Inicio
   escreval("Digite um número:")
   leia(numero)
   antecessor<- numero -1
   Escreval("O antecessor do número:", numero ," , é", antecessor)

Fimalgoritmo